### ISSUE TITLE
연구2. Default Grammar

### ISSUE THREAD

**Issue by hongjisung** [hongjisung/synKU#2]
Grammar가 별도로 주어지지 않은 경우
주어진 logic과 constraint하에서
함수 바디를 구성하는데 가장 효율적인 grammar를 찾아내는 것

**Comment by cushionbadak** [comment]
기본적으로 쓸 수 있는 문법의 경우 SyGuS Spec Appendix-B 에 이미 다 나와있는데, 가장 효율적인 문법을 찾는다는 뜻은 그 문법에서 필요없어 보이는 문법은 후보 프로그램 탐색 전에 빼버린다는 의미지?

**Comment by hongjisung** [comment]
ㅇㅇ 그런셈이지

**Comment by hongjisung** [comment]
SYGUS2.0문서에 있는 대로 적용
